// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocietySearch.Server.Data;

#nullable disable

namespace SocietySearch.Server.Migrations
{
    [DbContext(typeof(SocietySearchDbContext))]
    [Migration("20260820004601_AddManagerIdToSociety")]
    partial class AddManagerIdToSociety
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocietySearch.Server.Model.Domain.Amenities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8de2be25-2200-4754-ac84-1e7955bcccb8"),
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            Id = new Guid("0ccc5c1d-19c6-443e-a9ad-2c320acee3fa"),
                            Name = "Gym"
                        },
                        new
                        {
                            Id = new Guid("d0847646-fce2-4f68-80d3-cf28caac2d89"),
                            Name = "Clubhouse"
                        },
                        new
                        {
                            Id = new Guid("fdb8099b-54a2-4b55-8a00-575fc2c20130"),
                            Name = "Children's Play Area"
                        },
                        new
                        {
                            Id = new Guid("7d87193a-c059-428d-b1c8-2aa2df9874dc"),
                            Name = "CCTV"
                        },
                        new
                        {
                            Id = new Guid("989e00b5-0271-48b2-aa8a-14ace9d6b277"),
                            Name = "Parking"
                        },
                        new
                        {
                            Id = new Guid("6fc94294-f2e9-4653-8d89-9a48c050f45f"),
                            Name = "Library"
                        },
                        new
                        {
                            Id = new Guid("3928891d-c8f1-4348-ade7-8fe57534e8b4"),
                            Name = "Turf"
                        });
                });

            modelBuilder.Entity("SocietySearch.Server.Model.Domain.Society", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmenityIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstablishmentYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocietyImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Societies");
                });

            modelBuilder.Entity("SocietySearch.Server.Model.Domain.Units", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AvailabilityStatus")
                        .HasColumnType("bit");

                    b.Property<int>("AvailableUnits")
                        .HasColumnType("int");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId");

                    b.ToTable("Units", null, t =>
                        {
                            t.HasCheckConstraint("CK_Units_Type_AllowedValues", "[Type] IN ('1 BHK', '2 BHK', '3 BHK', '4 BHK', 'Penthouse', 'Studio')");
                        });
                });

            modelBuilder.Entity("SocietySearch.Server.Model.Domain.Units", b =>
                {
                    b.HasOne("SocietySearch.Server.Model.Domain.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Society");
                });
#pragma warning restore 612, 618
        }
    }
}
